elite_driver:
  use_fake: False
  loop_rate: 125
  auto_connect: True
  joint_name: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']
elite_controller:
  trajectory_service_name: joint_trajectory_movel
  interpolate_sample_time: 0.008